/**
 * BG3SE-macOS - Embedded Network Lua Scripts
 *
 * Contains Class.lua, NetChannel.lua, and NetworkManager.lua as C strings.
 * These are loaded at Lua state initialization to provide the Net.CreateChannel API.
 *
 * Issue #6: NetChannel API
 */

#ifndef LUA_NET_SCRIPTS_H
#define LUA_NET_SCRIPTS_H

// Class library (simple OOP support)
static const char *LUA_SCRIPT_CLASS =
"local _ClassLib = {}\n"
"\n"
"function _ClassLib.Create(defn)\n"
"    local cls = {}\n"
"    cls.__index = cls\n"
"\n"
"    for k,v in pairs(defn) do\n"
"        cls[k] = v\n"
"    end\n"
"\n"
"    function cls:New(...)\n"
"        local o = cls:Instantiate(...)\n"
"        setmetatable(o, self)\n"
"        return o\n"
"    end\n"
"\n"
"    return cls\n"
"end\n"
"\n"
"return _ClassLib\n";

// NetChannel class
static const char *LUA_SCRIPT_NETCHANNEL =
"local NetChannel = {}\n"
"\n"
"function NetChannel:Instantiate(module, channel)\n"
"    return {\n"
"        Module = module,\n"
"        Channel = channel\n"
"    }\n"
"end\n"
"\n"
"function NetChannel:SetHandler(handler)\n"
"    self.MessageHandler = handler\n"
"end\n"
"\n"
"function NetChannel:SetRequestHandler(handler)\n"
"    self.RequestHandler = handler\n"
"end\n"
"\n"
"function NetChannel:IsBinary()\n"
"    return Ext.Net.Version() >= 2\n"
"end\n"
"\n"
"function NetChannel:Stringify(msg)\n"
"    return Ext.Json.Stringify(msg)\n"
"end\n"
"\n"
"function NetChannel:DoSendToServer(message, handler)\n"
"    local msg = self:Stringify(message)\n"
"    Ext.Net.PostMessageToServer(self.Channel, msg, self.Module, handler, nil, self:IsBinary())\n"
"end\n"
"\n"
"function NetChannel:SendToServer(message)\n"
"    self:DoSendToServer(message, nil)\n"
"end\n"
"\n"
"function NetChannel:RequestToServer(message, handler)\n"
"    local replyHandler = function (reply, binary)\n"
"        handler(Ext.Json.Parse(reply))\n"
"    end\n"
"    self:DoSendToServer(message, replyHandler)\n"
"end\n"
"\n"
"function NetChannel:DoSendToClient(message, user, handler)\n"
"    local msg = self:Stringify(message)\n"
"    if type(user) == \"number\" then\n"
"        Ext.Net.PostMessageToUser(user, self.Channel, msg, self.Module, handler, nil, self:IsBinary())\n"
"    else\n"
"        Ext.Net.PostMessageToClient(user, self.Channel, msg, self.Module, handler, nil, self:IsBinary())\n"
"    end\n"
"end\n"
"\n"
"function NetChannel:SendToClient(message, user)\n"
"    self:DoSendToClient(message, user, nil)\n"
"end\n"
"\n"
"function NetChannel:RequestToClient(message, user, handler)\n"
"    local replyHandler = function (reply, binary)\n"
"        handler(Ext.Json.Parse(reply))\n"
"    end\n"
"    self:DoSendToClient(message, user, replyHandler)\n"
"end\n"
"\n"
"function NetChannel:Broadcast(message, excludeCharacter)\n"
"    local msg = self:Stringify(message)\n"
"    Ext.Net.BroadcastMessage(self.Channel, msg, excludeCharacter, self.Module, nil, nil, self:IsBinary())\n"
"end\n"
"\n"
"function NetChannel:OnMessage(e)\n"
"    local request = Ext.Json.Parse(e.Payload)\n"
"    if e.RequestId and e.RequestId ~= 0 then\n"
"        if self.RequestHandler then\n"
"            local ok, ret = xpcall(self.RequestHandler, debug.traceback, request, e.UserID)\n"
"            if ok then\n"
"                local reply = self:Stringify(ret)\n"
"                if Ext.IsServer() then\n"
"                    Ext.Net.PostMessageToUser(e.UserID, e.Channel, reply, e.Module, nil, e.RequestId, self:IsBinary())\n"
"                else\n"
"                    Ext.Net.PostMessageToServer(e.Channel, reply, e.Module, nil, e.RequestId, self:IsBinary())\n"
"                end\n"
"            else\n"
"                Ext.Print('[NetChannel] Request error: ' .. tostring(ret))\n"
"            end\n"
"        end\n"
"    else\n"
"        if self.MessageHandler then\n"
"            local ok, err = xpcall(self.MessageHandler, debug.traceback, request, e.UserID)\n"
"            if not ok then\n"
"                Ext.Print('[NetChannel] Message error: ' .. tostring(err))\n"
"            end\n"
"        end\n"
"    end\n"
"end\n"
"\n"
"return Class.Create(NetChannel)\n";

// NetworkManager singleton
static const char *LUA_SCRIPT_NETWORKMANAGER =
"local NetworkManager = {\n"
"    Channels = {},\n"
"    Initialized = false\n"
"}\n"
"\n"
"function NetworkManager:AddChannel(module, channel)\n"
"    if Ext.Mod and Ext.Mod.IsModLoaded and not Ext.Mod.IsModLoaded(module) then\n"
"        error('Creating network channel for nonexistent mod ' .. module)\n"
"    end\n"
"    local ch = NetChannel:New(module, channel)\n"
"    self:RegisterChannel(ch)\n"
"    return ch\n"
"end\n"
"\n"
"function NetworkManager:RegisterChannel(channel)\n"
"    if self.Channels[channel.Module] == nil then\n"
"        self.Channels[channel.Module] = {}\n"
"    end\n"
"    if self.Channels[channel.Module][channel.Channel] ~= nil then\n"
"        error('Channel ' .. channel.Channel .. ' for module ' .. channel.Module .. ' already registered')\n"
"    end\n"
"    self.Channels[channel.Module][channel.Channel] = channel\n"
"end\n"
"\n"
"function NetworkManager:RegisterEvents()\n"
"    if self.Initialized then return end\n"
"    self.Initialized = true\n"
"    if Ext.Events and Ext.Events.NetModMessage then\n"
"        Ext.Events.NetModMessage:Subscribe(function (e)\n"
"            self:MessageReceived(e)\n"
"        end)\n"
"    end\n"
"end\n"
"\n"
"function NetworkManager:MessageReceived(e)\n"
"    if not e.Module or e.Module == '' then return end\n"
"    if not self.Channels[e.Module] or not self.Channels[e.Module][e.Channel] then\n"
"        return\n"
"    end\n"
"    local channel = self.Channels[e.Module][e.Channel]\n"
"    channel:OnMessage(e)\n"
"end\n"
"\n"
"return NetworkManager\n";

// Net.CreateChannel wrapper (creates global Net table with CreateChannel function)
// Note: This string exceeds ISO C99's 4095-char minimum requirement, but all
// modern compilers (Clang, GCC) handle longer strings fine. Suppress the warning.
#ifdef __clang__
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Woverlength-strings"
#endif
#ifdef __GNUC__
#ifndef __clang__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Woverlength-strings"
#endif
#endif

static const char *LUA_SCRIPT_NET_INIT =
"-- Initialize Net library globals\n"
"Class = (function()\n"
"    local _ClassLib = {}\n"
"    function _ClassLib.Create(defn)\n"
"        local cls = {}\n"
"        cls.__index = cls\n"
"        for k,v in pairs(defn) do\n"
"            cls[k] = v\n"
"        end\n"
"        function cls:New(...)\n"
"            local o = cls:Instantiate(...)\n"
"            setmetatable(o, self)\n"
"            return o\n"
"        end\n"
"        return cls\n"
"    end\n"
"    return _ClassLib\n"
"end)()\n"
"\n"
"-- NetChannel class\n"
"NetChannel = (function()\n"
"    local NetChannel = {}\n"
"    function NetChannel:Instantiate(module, channel)\n"
"        return { Module = module, Channel = channel }\n"
"    end\n"
"    function NetChannel:SetHandler(handler) self.MessageHandler = handler end\n"
"    function NetChannel:SetRequestHandler(handler) self.RequestHandler = handler end\n"
"    function NetChannel:IsBinary() return Ext.Net.Version() >= 2 end\n"
"    function NetChannel:Stringify(msg) return Ext.Json.Stringify(msg) end\n"
"    function NetChannel:DoSendToServer(message, handler)\n"
"        local msg = self:Stringify(message)\n"
"        Ext.Net.PostMessageToServer(self.Channel, msg, self.Module, handler, nil, self:IsBinary())\n"
"    end\n"
"    function NetChannel:SendToServer(message) self:DoSendToServer(message, nil) end\n"
"    function NetChannel:RequestToServer(message, handler)\n"
"        self:DoSendToServer(message, function(reply) handler(Ext.Json.Parse(reply)) end)\n"
"    end\n"
"    function NetChannel:DoSendToClient(message, user, handler)\n"
"        local msg = self:Stringify(message)\n"
"        if type(user) == 'number' then\n"
"            Ext.Net.PostMessageToUser(user, self.Channel, msg, self.Module, handler, nil, self:IsBinary())\n"
"        else\n"
"            Ext.Net.PostMessageToClient(user, self.Channel, msg, self.Module, handler, nil, self:IsBinary())\n"
"        end\n"
"    end\n"
"    function NetChannel:SendToClient(message, user) self:DoSendToClient(message, user, nil) end\n"
"    function NetChannel:RequestToClient(message, user, handler)\n"
"        self:DoSendToClient(message, user, function(reply) handler(Ext.Json.Parse(reply)) end)\n"
"    end\n"
"    function NetChannel:Broadcast(message, excludeCharacter)\n"
"        Ext.Net.BroadcastMessage(self.Channel, self:Stringify(message), excludeCharacter, self.Module, nil, nil, self:IsBinary())\n"
"    end\n"
"    function NetChannel:OnMessage(e)\n"
"        local request = Ext.Json.Parse(e.Payload)\n"
"        if e.RequestId and e.RequestId ~= 0 then\n"
"            if self.RequestHandler then\n"
"                local ok, ret = xpcall(self.RequestHandler, debug.traceback, request, e.UserID)\n"
"                if ok then\n"
"                    local reply = self:Stringify(ret)\n"
"                    if Ext.IsServer() then\n"
"                        Ext.Net.PostMessageToUser(e.UserID, e.Channel, reply, e.Module, nil, e.RequestId, self:IsBinary())\n"
"                    else\n"
"                        Ext.Net.PostMessageToServer(e.Channel, reply, e.Module, nil, e.RequestId, self:IsBinary())\n"
"                    end\n"
"                end\n"
"            end\n"
"        else\n"
"            if self.MessageHandler then\n"
"                xpcall(self.MessageHandler, debug.traceback, request, e.UserID)\n"
"            end\n"
"        end\n"
"    end\n"
"    return Class.Create(NetChannel)\n"
"end)()\n"
"\n"
"-- NetworkManager singleton\n"
"_G._NetworkManager = {\n"
"    Channels = {},\n"
"    Initialized = false,\n"
"    AddChannel = function(self, module, channel)\n"
"        local ch = NetChannel:New(module, channel)\n"
"        self:RegisterChannel(ch)\n"
"        return ch\n"
"    end,\n"
"    RegisterChannel = function(self, channel)\n"
"        if self.Channels[channel.Module] == nil then\n"
"            self.Channels[channel.Module] = {}\n"
"        end\n"
"        self.Channels[channel.Module][channel.Channel] = channel\n"
"    end,\n"
"    RegisterEvents = function(self)\n"
"        if self.Initialized then return end\n"
"        self.Initialized = true\n"
"        if Ext.Events and Ext.Events.NetModMessage then\n"
"            Ext.Events.NetModMessage:Subscribe(function(e)\n"
"                self:MessageReceived(e)\n"
"            end)\n"
"        end\n"
"    end,\n"
"    MessageReceived = function(self, e)\n"
"        if not e.Module or e.Module == '' then return end\n"
"        if not self.Channels[e.Module] or not self.Channels[e.Module][e.Channel] then return end\n"
"        self.Channels[e.Module][e.Channel]:OnMessage(e)\n"
"    end\n"
"}\n"
"\n"
"-- Create global Net table with CreateChannel\n"
"Net = setmetatable({}, {\n"
"    __index = function(t, k)\n"
"        if k == 'CreateChannel' then\n"
"            return function(module, channel)\n"
"                if channel == nil then channel = module; module = '' end\n"
"                _G._NetworkManager:RegisterEvents()\n"
"                return _G._NetworkManager:AddChannel(module, channel)\n"
"            end\n"
"        end\n"
"        return Ext.Net[k]\n"
"    end\n"
"})\n"
"\n"
"-- NOTE: Ext.Net.CreateChannel is intentionally NOT exposed here. Doing so lets\n"
"-- MCM create/use net channels, which triggers the port's net-message factory\n"
"-- registration. That path is broken on the current game version (the RakNet\n"
"-- GetMessage Dobby hook fails to install), and activating it corrupts the game\n"
"-- message-factory pool, crashing the game in net::MessageFactory::GetFreeMessage\n"
"-- during ecl::CharacterProtocol::PostUpdate. Re-enable only once the net hook\n"
"-- works. The global Net.CreateChannel remains available for code that opts in.\n"
"\n"
"Ext.Print('[Net] Network library initialized')\n";

#ifdef __clang__
#pragma clang diagnostic pop
#endif
#ifdef __GNUC__
#ifndef __clang__
#pragma GCC diagnostic pop
#endif
#endif

#endif /* LUA_NET_SCRIPTS_H */
