#!/usr/bin/env python3
"""Generate src/entity/component_short_names.h from the Windows BG3SE headers.

Windows BG3SE names components by their ExtComponentType ("Health",
"ServerCharacter", "StatusContainer"); the engine names them by class
("eoc::HealthComponent", "esv::Character", ...). This emits the mapping so
Ext.Entity APIs accept the Windows names.

Usage: tools/gen_component_short_names.py <path-to-bg3se-checkout> > src/entity/component_short_names.h
"""

import re
import sys
from pathlib import Path

PATTERNS = [
    # DEFINE_COMPONENT(Short, "engine::Class") / ONEFRAME / PROXY
    (re.compile(r'DEFINE_(?:ONEFRAME_|PROXY_)?COMPONENT\(\s*(\w+)\s*,\s*"([^"]+)"'),
     lambda m: (m.group(1), m.group(2))),
    # DEFINE_TAG_COMPONENT(ns, Name, Short) / ONEFRAME_TAG
    (re.compile(r'DEFINE_(?:ONEFRAME_)?TAG_COMPONENT\(\s*([\w:]+)\s*,\s*(\w+)\s*,\s*(\w+)\s*\)'),
     lambda m: (m.group(3), f"{m.group(1)}::{m.group(2)}")),
    # DEFN_BOOST(Name, BoostType, {...}) -> NameBoost / eoc::NameBoostComponent
    (re.compile(r'DEFN_BOOST\(\s*(\w+)\s*,'),
     lambda m: (f"{m.group(1)}Boost", f"eoc::{m.group(1)}BoostComponent")),
]


def collect(root: Path) -> dict:
    names = {}
    for path in sorted((root / "BG3Extender/GameDefinitions").rglob("*.h")):
        text = path.read_text(errors="ignore")
        for rx, pick in PATTERNS:
            for m in rx.finditer(text):
                short, full = pick(m)
                if short in ("componentType", "name"):   # the macro definitions themselves
                    continue
                prev = names.setdefault(short, full)
                if prev != full:
                    raise SystemExit(f"conflicting names for {short}: {prev} vs {full}")
    return names


def main() -> None:
    names = collect(Path(sys.argv[1]))
    print("/* Generated by tools/gen_component_short_names.py from the Windows BG3SE")
    print(" * headers (DEFINE_*COMPONENT, DEFN_BOOST). Do not edit by hand. */")
    print("#ifndef COMPONENT_SHORT_NAMES_H")
    print("#define COMPONENT_SHORT_NAMES_H\n")
    print("typedef struct { const char *shortName; const char *engineName; } ComponentShortName;\n")
    print("static const ComponentShortName g_ComponentShortNames[] = {")
    for short in sorted(names):
        print(f'    {{ "{short}", "{names[short]}" }},')
    print("};\n")
    print("#define COMPONENT_SHORT_NAME_COUNT "
          "(sizeof(g_ComponentShortNames) / sizeof(g_ComponentShortNames[0]))\n")
    print("#endif")


if __name__ == "__main__":
    main()
